export const SUCCESS_FAILURE = {
  SUCCESS_FAILURE_REQUESTED: "SEARCH_LOCATIONS_REQUESTED",
  SUCCESS_FAILURE_FETCHED: "SEARCH_LOCATIONS_FETCHED",
  SUCCESS_FAILURE_ERROR: "SEARCH_LOCATIONS_ERROR",
  SUCCESS_FAILURE_UPDATE: "SEARCH_INPUT_UPDATE",
};

// export const locationsConstants = {
// 	LOCATION_REQUESTED: 'LOCATION_REQUESTED',
// 	LOCATION_FETCHED: 'LOCATION_FETCHED',
// 	LOCATION_ERROR: 'LOCATION_ERROR',
// };
